version: '3'
services:

  api:
    build: .
    container_name: ranking_api
    ports:
      - "5001:5001"
    environment:
      SERVER_PORT: 5001
      POSTGRES_HOST: postgresdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ranking-db
      PGPORT: 5432

    restart: always
    depends_on:
      postgresdb:
        condition: service_healthy

  postgresdb:
    image: postgres:15.5-bullseye
    hostname: postgresdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ranking-db
    volumes:
      - ./volumes/postgres-ranking-app:/var/lib/postgresql/data

    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -U postgres -d ranking-db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./src/main/client/
      args:
        API_URL: http://localhost:5001
    container_name: ranking_app_front
    ports:
      - "5002:5002"

    restart: always
    depends_on:
      - api
