server:
    port: ${SERVER_PORT}

spring:
    datasource:
        url: jdbc:postgresql://${POSTGRES_HOST}:${PGPORT}/${POSTGRES_DB}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: none

        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
    flyway:
        baseline-on-migrate: true
        baseline-version: 0
#        url: jdbc:postgresql://${POSTGRES_HOST}:${PGPORT}/${POSTGRES_DB}
#        user: ${POSTGRES_USER}
#        password: ${POSTGRES_PASSWORD}
#


