version: '3'
services:

  app:
    build:
      context: .
      args:
        API_URL: http://localhost:5001
    container_name: ranking_app_front
    ports:
      - "5002:5002"   

    restart: always


